language: python
python:
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - nosetests -v --with-coverage --cover-tests --cover-package=pyaxonaut pyaxonaut/tests

after_success:
  - codecov