class QuoteLine:
    product_id = None
    product_internal_id = None
    product_name = ""
    product_code = ""
    title = ""
    details = ""
    quantity = ""
    unit_price = ""
    tax_rate = ""
    line_discount_amount = ""
    line_discount_amount_with_tax = ""
    line_discount_unit_is_percent = ""
    tax_amount = None
    pretax_amount = None
    total_amount = None

    def __init__(self, json_quote_line):
        self.product_id = json_quote_line.get('productId')
        self.product_internal_id = json_quote_line.get('productInternalId')
        self.product_name = json_quote_line.get('productName')
        self.product_code = json_quote_line.get('productCode')
        self.title = json_quote_line.get('title')
        self.details = json_quote_line.get('details')
        self.quantity = json_quote_line.get('quantity')
        self.unit_price = json_quote_line.get('unitPrice')
        self.tax_rate = json_quote_line.get('taxRate')
        self.line_discount_amount = json_quote_line.get('lineDiscountAmount')
        self.line_discount_amount_with_tax = json_quote_line.get('lineDiscountAmountWithTax')
        self.line_discount_unit_is_percent = json_quote_line.get('lineDiscountUnitIsPercent')
        self.tax_amount = json_quote_line.get('taxAmount')
        self.pretax_amount = json_quote_line.get('pretaxAmount')
        self.total_amount = json_quote_line.get('totalAmount')
